---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "eirini"
data:
  opi.yaml: |
    opi:
      kube_namespace: {{ .Values.opi.namespace }}
      nats_ip: "{{ .Values.opi.nats_address }}"
      nats_port: 4222
      cc_internal_api: "{{ .Values.opi.cc_internal_api }}"
      cc_certs_secret_name: "{{ .Values.opi.cc_certs_secret_name }}"
      registry_address: "{{ .Values.opi.registry_address }}"
      registry_secret_name: "{{ .Values.opi.registry_secret_name }}"
      eirini_address: "https://eirini-opi.{{ .Release.Namespace }}.svc.cluster.local:8085"
      {{- if .Values.opi.stager }}
      downloader_image: "{{ .Values.opi.stager.downloader_image }}:{{ .Values.opi.image_tag }}"
      executor_image: "{{ .Values.opi.stager.executor_image }}:{{ .Values.opi.image_tag }}"
      uploader_image: "{{ .Values.opi.stager.uploader_image }}:{{ .Values.opi.image_tag }}"
      {{- else }}
      downloader_image: eirini/recipe-downloader@{{ .Files.Get "versions/staging-downloader" }}
      executor_image: eirini/recipe-executor@{{ .Files.Get "versions/staging-executor" }}
      uploader_image: eirini/recipe-uploader@{{ .Files.Get "versions/staging-uploader" }}
      {{- end }}
      loggregator_address: "{{ .Values.opi.loggregator_address }}"
      loggergator_cert_path: "/workspace/jobs/opi/secrets/doppler.crt"
      loggregator_key_path: "/workspace/jobs/opi/secrets/doppler.key"
      loggregator_ca_path: "/workspace/jobs/opi/secrets/doppler.ca"
      cc_cert_path: "/workspace/jobs/opi/secrets/cc.crt"
      cc_key_path: "/workspace/jobs/opi/secrets/cc.key"
      cc_ca_path: "/workspace/jobs/opi/secrets/cc.ca"
      rootfs_version: "{{ .Values.opi.rootfs_version }}"
      client_ca_path: "/workspace/jobs/opi/secrets/eirini-client-ca.crt"
      server_cert_path: "/workspace/jobs/opi/secrets/eirini-server.crt"
      server_key_path: "/workspace/jobs/opi/secrets/eirini-server.key"
      tls_port: 8085
      disk_limit_mb: {{ .Values.opi.disk_limit_mb }}
