---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "eirini"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: "eirini"
  template:
    metadata:
      labels:
        name: "eirini"
        eirinifs_version: "{{  .Values.global.rootfs_version  }}"
    spec:
      dnsPolicy: "ClusterFirst"
      serviceAccountName: "opi"
      volumes:
        - name: config-map-volume
          configMap:
            name: "eirini"
            items:
            - key: opi.yml
              path: opi.yml
        - name: cf-secrets
          secret:
            secretName: "{{ .Values.scfSecretName }}"
            items:
            - key: doppler-cert
              path: doppler.crt
            - key: doppler-cert-key
              path: doppler.key
            - key: internal-ca-cert
              path: doppler.ca
            - key: cc-server-crt
              path: cc.crt
            - key: cc-server-crt-key
              path: cc.key
            - key: internal-ca-cert
              path: cc.ca
            - key: eirini-client-crt
              path: eirini-server.crt
            - key: eirini-client-crt-key
              path: eirini-server.key
            - key: internal-ca-cert
              path: eirini-client-ca.crt
      securityContext:
        runAsNonRoot: false
      containers:
      - name: opi
        {{- if .Values.opi.image }}
        image: {{ .Values.opi.image }}:{{ .Values.opi.image_tag }}
        {{- else }}
        image: eirini/opi@{{ .Files.Get "versions/opi" }}
        {{- end }}
        imagePullPolicy: Always
        volumeMounts:
        - name: config-map-volume
          mountPath: /workspace/jobs/opi/config
        - name: cf-secrets
          mountPath: /workspace/jobs/opi/secrets
        ports:
        - containerPort: 8085
        resources:
          requests:
            cpu: 20m
            memory: 20Mi
